<?php

declare(strict_types=1);

namespace Swiftphp\Framework\Database\Schema;

use Swiftphp\Framework\Database\QueryBuilder\Grammar;
use InvalidArgumentException;

final class SchemaBuilder
{
    public function __construct(
        private readonly Grammar $grammar,
    ) {
    }

    /**
     * Compiles the blueprint structure into an array of executable DDL steps.
     * * @return string[]
     */
    public function create(Blueprint $blueprint): array
    {
        $dialect = $this->grammar->getDialect();
        $tableLines = [];
        $postStatements = [];

        // 1. Compile Columns
        foreach ($blueprint->columns as $column) {
            $tableLines[] = $this->compileColumn($column, $dialect);
        }

        // 2. Compile Indexes & Unique Key Constraints
        foreach ($blueprint->indexes as $index) {
            $name = $index['name'] ?? sprintf('%s_%s_%s', $blueprint->table, implode('_', $index['columns']), $index['type']);
            $cols = $this->grammar->columnize($index['columns']);

            if ($dialect === 'pgsql') {
                if ($index['type'] === 'unique') {
                    // Postgres handles unique declarations inside constraints blocks smoothly
                    $tableLines[] = sprintf('CONSTRAINT %s UNIQUE (%s)', $this->grammar->wrap($name), $cols);
                } else {
                    // Regular indexes MUST be executed as a separate statement downstream in Postgres
                    $postStatements[] = sprintf(
                        'CREATE INDEX %s ON %s (%s)',
                        $this->grammar->wrap($name),
                        $this->grammar->wrap($blueprint->table),
                        $cols
                    );
                }
            } else {
                // Inline placement works perfectly for MySQL
                $tableLines[] = match ($index['type']) {
                    'index' => sprintf('INDEX %s (%s)', $this->grammar->wrap($name), $cols),
                    'unique' => sprintf('UNIQUE KEY %s (%s)', $this->grammar->wrap($name), $cols),
                };
            }
        }

        // 3. Compile Foreign Keys
        foreach ($blueprint->foreignKeys as $fk) {
            $tableLines[] = $this->compileForeignKey($fk);
        }

        $createTableSql = sprintf(
            "CREATE TABLE %s (\n    %s\n)",
            $this->grammar->wrap($blueprint->table),
            implode(",\n    ", array_filter($tableLines))
        );

        return array_merge([$createTableSql], $postStatements);
    }

    private function compileColumn(ColumnDefinition $col, string $dialect): string
    {
        // Route primary auto-increment sequences cleanly per dialect
        if ($col->autoIncrement && $col->type === 'bigint') {
            if ($dialect === 'pgsql') {
                return $this->grammar->wrap($col->name) . ' BIGSERIAL PRIMARY KEY';
            }
            return $this->grammar->wrap($col->name) . ' BIGINT AUTO_INCREMENT PRIMARY KEY';
        }

        $type = match ($col->type) {
            'uuid' => $dialect === 'pgsql' ? 'UUID' : 'CHAR(36)',
            'string' => "VARCHAR({$col->length})",
            'text' => 'TEXT',
            'integer' => 'INT',
            'boolean' => $dialect === 'pgsql' ? 'BOOLEAN' : 'TINYINT(1)',
            'timestamp' => 'TIMESTAMP',
            'bigint' => 'BIGINT',
            default => throw new InvalidArgumentException("Unknown type {$col->type}"),
        };

        if ($col->autoIncrement && $col->type === 'bigint') {
            if ($dialect === 'pgsql') {
                return $this->grammar->wrap($col->name) . ' BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
            }
            return $this->grammar->wrap($col->name) . ' BIGINT AUTO_INCREMENT PRIMARY KEY';
        }

        $type = match ($col->type) {
            'uuid' => $dialect === 'pgsql' ? 'UUID' : 'CHAR(36)',
            'string' => "VARCHAR({$col->length})",
            'text' => 'TEXT',
            'integer' => 'INT',
            'boolean' => $dialect === 'pgsql' ? 'BOOLEAN' : 'TINYINT(1)',
            'timestamp' => 'TIMESTAMP',
            'bigint' => 'BIGINT',
            default => throw new InvalidArgumentException("Unknown type {$col->type}"),
        };

        $sql = $this->grammar->wrap($col->name) . " $type";

        if (!$col->nullable) {
            $sql .= ' NOT NULL';
        }

        if ($col->default !== null) {
            $sql .= ' DEFAULT ' . $this->quoteDefault($col->default, $dialect);
        }

        if ($col->primary && !$col->autoIncrement) {
            $sql .= ' PRIMARY KEY';
        }

        return $sql;
    }

    private function compileForeignKey(ForeignKeyDefinition $fk): string
    {
        if (!$fk->references || !$fk->on) {
            throw new InvalidArgumentException('Foreign key incomplete definition.');
        }

        return sprintf(
            'FOREIGN KEY (%s) REFERENCES %s(%s) ON DELETE %s ON UPDATE %s',
            $this->grammar->wrap($fk->column),
            $this->grammar->wrap($fk->on),
            $this->grammar->wrap($fk->references),
            $fk->onDelete,
            $fk->onUpdate
        );
    }

    private function quoteDefault(mixed $value, string $dialect): string
    {
        if ($value === 'CURRENT_TIMESTAMP') {
            return 'CURRENT_TIMESTAMP';
        }

        if (is_bool($value)) {
            if ($dialect === 'pgsql') {
                return $value ? 'TRUE' : 'FALSE';
            }
            return $value ? '1' : '0';
        }

        if (is_string($value)) {
            return "'" . str_replace("'", "''", $value) . "'";
        }

        return (string) $value;
    }
}